### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by dianashk** [dianashk/batch-search-app#1]
* [ ] build in analytics about usage and each page
* [ ] add licensing info page (from menu?)
* [ ] add documentation (from menu?)
* [ ] support link (from menu and possibly bubbles throughout)
* [x] add padding below all screens to allow scroll
* [x] catch errors and don't show them on map (maybe separate log window)
* [x] login is probably important to avoid stolen keys
    * already being done in Tangram Play (borrow code)
* [x] add pricing and timing information
    * @souperneon will help with flow
* [x] add all the filter params
    * boundary.country
    * boundary.circle
    * sources
    * layers
* [x] get rid of stock menu
* [x] update status bar icon
* [x] add progress words to bar
* [x] Change 'map columns' button to 'next'
* [x] change 'ignore' to 'select' for dropdown in the mapping screen and ignore the columns users don't select

@souperneon
* [x] change default window size 
   * main window
   * auth window
* [x] Add padding to tables
* [x]  Make table more narrow
* [x] Icon for the app
* [x] Work with select file screen
* [x] Make a parent div and put all content of screens inside it- 80%
* [x] Make text wrap when screensize is smaller
* [x] Replace pngs for results

**Comment by dianashk** [comment]
- [ ]  create log file during processing and link to it in case of error from an error alert (styleguide)

**Comment by dianashk** [comment]
- [x] change buttons on map view to have the left one say `Start Over` and the right one say `View Your Results`

**Comment by dianashk** [comment]
- [x] add leaflet legend to the map

**Comment by dianashk** [comment]
- [ ] add check for newer version and prompt users to download it via link
